# Generated by Django 4.1 on 2023-02-10 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='', verbose_name='/media')),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Articl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='/media')),
            ],
        ),
        migrations.CreateModel(
            name='HomeReaload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='', verbose_name='/meadi')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='', verbose_name='/media')),
                ('title', models.CharField(max_length=100)),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('OFFprice', models.CharField(blank=True, max_length=20, null=True)),
                ('des', models.TextField()),
                ('pic', models.ImageField(upload_to='', verbose_name='/media')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='', verbose_name='/media')),
                ('titile', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='servicesDescript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='', verbose_name='/media')),
                ('name', models.CharField(max_length=50)),
                ('Expertise', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Why_Choose_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='', verbose_name='/media')),
                ('des', models.TextField()),
                ('pic1', models.ImageField(upload_to='', verbose_name='/media')),
                ('title1', models.CharField(max_length=100)),
                ('pic2', models.ImageField(upload_to='', verbose_name='/media')),
                ('title2', models.CharField(max_length=100)),
                ('pic3', models.ImageField(upload_to='', verbose_name='/media')),
                ('title3', models.CharField(max_length=100)),
                ('pic4', models.ImageField(upload_to='', verbose_name='/media')),
                ('title4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work_with_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('adrrs', models.CharField(max_length=80)),
                ('resuame', models.ImageField(upload_to='', verbose_name='/media')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computerService.products')),
            ],
        ),
    ]
